

services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: maintenance_backend

    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile

    container_name: maintenance_frontend

    ports:
      - "8501:8501"

    depends_on:
      - backend